// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sutmmlryzosbasksamqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dG1tbHJ5em9zYmFza3NhbXF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1ODI3MTQsImV4cCI6MjA3NDE1ODcxNH0.4Tka6Y5Wrqlc1mNmmnVfuo3jrMbI2vXRaQS4_Vvu1XI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});